config/routes.rb
Rails.application.routes.draw do
  ###########################################################################
  # Routes take the form                                                    #
  #   http-request-method '/url', to: 'controller#action', as: named_route  #
  # where 'named_route' is usually in the form of action_controller.        #
  # Request methods for this application are limited to either GET or POST. #
  ###########################################################################

  #############################################################
  # HTML ROUTES - HTML IS RENDERED AND NO MODIFICATIONS OCCUR #
  #############################################################

  # public pages
  get '/', to: 'html#home', as: :root
  get '/about', to: 'html#about_doc', as: :about
  get '/docs/user', to: 'html#user_doc', as: :user_doc
  get '/docs/developer', to: 'html#developer_doc', as: :developer_doc
  get '/signup', to: 'html#new_user_form', as: :signup_form
  get '/user/new_user', to: 'html#new_user_form', as: :new_user_form

  # participant pages
  get '/login', to: 'html#login_form', as: :login_form
  get '/user/:id', to: 'html#show_user', as: :show_user
  get '/user/:id/edit', to: 'html#edit_user_form', as: :edit_user_form
  get '/event/new_event', to: 'html#new_event_form', as: :new_event_form
  get '/event/:id', to: 'html#show_event', as: :show_event
  get '/join/:event_id', to: 'users#join_event', as: :join_event
  get '/visit/:tag', to: 'users#visit_location', as: :visit_location
  get '/user/:id/delete', to: 'users#delete_user', as: :delete_user

  # owner pages
  get '/event/:id/edit', to: 'html#edit_event_form', as: :edit_event_form
  get '/location/new_location_form', to: 'html#new_location_form', as: :new_location_form
  get '/location/:id', to: 'html#show_location', as: :show_location
  get '/location/:id/edit', to: 'html#edit_location_form', as: :edit_location_form

  # admin pages
  get '/events', to: 'html#show_all_events', as: :show_all_events
  get '/locations', to: 'html#show_all_locations', as: :show_all_locations
  get '/users', to: 'html#show_all_users', as: :show_all_users
  get '/setup', to: 'html#new_option_form', as: :new_option_form
  get '/options/edit', to: 'html#edit_option_form', as: :edit_option_form

  ###############################################################
  # NORMAL ROUTES - NOTHING RENDERED; MODIFICATIONS MIGHT OCCUR #
  ###############################################################

  # public routes
  post '/user/create_user', to: 'users#create_user', as: :create_user
  post '/user/:id/update', to: 'users#update_user', as: :update_user
  post '/session/create', to: 'sessions#create_session', as: :create_session

  # participant routes
  get '/logout', to: 'sessions#update_session', as: :logout
  get '/leave/:event_id', to: 'users#leave_event', as: :leave_event

  # owner routes
  post '/event/create_event', to: 'events#create_event', as: :create_event
  post '/event/:id/update', to: 'events#update_event', as: :update_event
  get '/event/:id/delete', to: 'events#delete_event', as: :delete_event
  post '/location/create_location', to: 'locations#create_location', as: :create_location
  post '/location/:id/update', to: 'locations#update_location', as: :update_location
  get '/location/:id/delete', to: 'locations#delete_location', as: :delete_location
  
  # admin routes
  post '/setup', to: 'options#create_option', as: :create_option
  post '/options/edit', to: 'options#update_option', as: :update_option
end

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-exa
mple-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><strong class="school-logo"><%= Option.last.logo %></strong></a>
      <div class="navbar-text"><strong class=""><%= app_name %></strong></div>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if not @current_user.guest? %>
            <li><%= link_to 'Dashboard', show_user_path(@current_user) %></li>
        <% end %>
        <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Help <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'About', about_path %></li>
            <li><%= link_to 'User Docs', user_doc_path %></li>
            <li><%= link_to 'Developer Docs', developer_doc_path %></li>
          </ul>
        </li>
        <% if @current_user.guest? %>
            <li><%= link_to 'Signup', signup_form_path %></li>
            <li><%= link_to 'Login', login_form_path %></li>
        <% elsif @current_user.participant? or @current_user.owner? %>
            <% if @current_user.admin? %>
                <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'Events', show_all_events_path %></li>
                    <li><%= link_to 'Locations', show_all_locations_path %></li>
                    <li><%= link_to 'Users', show_all_users_path %></li>
                  </ul>
                </li>
            <% end %>
            <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="glyphicon glyphicon-user" aria-hidden="true"></i> <%= @current_user.email %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Account', edit_user_form_path(@current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Logout', logout_path %></li>
              </ul>
            </li>
        <% end %>
      </ul>
    </div> <!-- /.navbar-collapse -->
  </div> <!-- /.container-fluid -->
</nav>