config/routes.rb
Rails.application.routes.draw do
  ###########################################################################
  # Routes take the form                                                    #
  #   http-request-method '/url', to: 'controller#action', as: named_route  #
  # where 'named_route' is usually in the form of action_controller.        #
  # Request methods for this application are limited to either GET or POST. #
  ###########################################################################

  #############################################################
  # HTML ROUTES - HTML IS RENDERED AND NO MODIFICATIONS OCCUR #
  #############################################################

  # public pages
  get '/', to: 'html#home', as: :root
  get '/about', to: 'html#about_doc', as: :about
  get '/docs/user', to: 'html#user_doc', as: :user_doc
  get '/docs/developer', to: 'html#developer_doc', as: :developer_doc
  get '/signup', to: 'html#new_user_form', as: :signup_form
  get '/user/new_user', to: 'html#new_user_form', as: :new_user_form

  # participant pages
  get '/login', to: 'html#login_form', as: :login_form
  get '/user/:id', to: 'html#show_user', as: :show_user
  get '/user/:id/edit', to: 'html#edit_user_form', as: :edit_user_form
  get '/event/new_event', to: 'html#new_event_form', as: :new_event_form
  get '/event/:id', to: 'html#show_event', as: :show_event
  get '/join/:event_id', to: 'users#join_event', as: :join_event
  get '/visit/:tag', to: 'users#visit_location', as: :visit_location
  get '/user/:id/delete', to: 'users#delete_user', as: :delete_user

  # owner pages
  get '/event/:id/edit', to: 'html#edit_event_form', as: :edit_event_form
  get '/location/new_location_form', to: 'html#new_location_form', as: :new_location_form
  get '/location/:id', to: 'html#show_location', as: :show_location
  get '/location/:id/edit', to: 'html#edit_location_form', as: :edit_location_form

  # admin pages
  get '/events', to: 'html#show_all_events', as: :show_all_events
  get '/locations', to: 'html#show_all_locations', as: :show_all_locations
  get '/users', to: 'html#show_all_users', as: :show_all_users
  get '/setup', to: 'html#new_option_form', as: :new_option_form
  get '/options/edit', to: 'html#edit_option_form', as: :edit_option_form

  ###############################################################
  # NORMAL ROUTES - NOTHING RENDERED; MODIFICATIONS MIGHT OCCUR #
  ###############################################################

  # public routes
  post '/user/create_user', to: 'users#create_user', as: :create_user
  post '/user/:id/update', to: 'users#update_user', as: :update_user
  post '/session/create', to: 'sessions#create_session', as: :create_session

  # participant routes
  get '/logout', to: 'sessions#update_session', as: :logout
  get '/leave/:event_id', to: 'users#leave_event', as: :leave_event

  # owner routes
  post '/event/create_event', to: 'events#create_event', as: :create_event
  post '/event/:id/update', to: 'events#update_event', as: :update_event
  get '/event/:id/delete', to: 'events#delete_event', as: :delete_event
  post '/location/create_location', to: 'locations#create_location', as: :create_location
  post '/location/:id/update', to: 'locations#update_location', as: :update_location
  get '/location/:id/delete', to: 'locations#delete_location', as: :delete_location
  
  # admin routes
  post '/setup', to: 'options#create_option', as: :create_option
  post '/options/edit', to: 'options#update_option', as: :update_option
end

app/controllers/html_controller.rb
class HtmlController < ApplicationController
=begin
= DEVELOPER

= HTML CONTROLLER

  The HtmlController contains all the actions that are intended to render actual HTML. This is a departure from the normal
  separation of concerns encountered in a Rails app, but the administrators found this organization to be just as useful.

  If an action is intended to render HTML, then it should be included in this controller. For example, the new_user_form action
  renders an HTML form to create a new account. The actual creation of the user object and persistence to the database
  is handled via the normal user controller.

=end
  
  skip_before_action :install, only: :new_user_form
  ##################
  # PUBLIC ACTIONS #
  ##################

  def home
    @current_events = Event.current
    @upcoming_events = Event.upcoming
  end

  def about_doc
  end

  def user_doc
  end

  def developer_doc
  end

  def new_user_form
    @user = User.new
  end

  def login_form
  end

  def visit_location_form
    @location = Location.find_by_tag(params[:tag])
  end

  #######################
  # PARTICIPANT ACTIONS #
  #######################

  def show_user
    @user = User.find(params[:id])
  end

  def edit_user_form
    @user = User.find(params[:id])
  end

  def show_event
    @event = Event.find(params[:id])
  end

  #################
  # OWNER ACTIONS #
  #################

  def new_event_form
    @event = Event.new
    @locations = Location.joins(:owner).where(users: {id: session[:user_id]})
  end

  def edit_event_form
    @event = Event.find(params[:id])
    @locations = Location.joins(:owner).where(users: {id: session[:user_id]})
    
    unless @event.owner.include? @current_user or @current_user.admin? 
      flash[:danger] = Messages::ErrorMessages::UnauthorizedAccess
      redirect_to show_user_path(@current_user)
    end
  end

  def new_location_form
    @location = Location.new
  end

  def show_location
    @location = Location.find(params[:id])
    unless @location.owner.include? @current_user or @current_user.admin?
      flash[:danger] = Messages::ErrorMessages::UnauthorizedAccess
      redirect_to show_user_path(@current_user)
    end
  end

  def edit_location_form
    @location = Location.find(params[:id])
    unless @location.owner.include? @current_user or @current_user.admin?
      flash[:danger] = Messages::ErrorMessages::UnauthorizedAccess
      redirect_to show_user_path(@current_user)
    end
  end

  #################
  # ADMIN ACTIONS #
  #################

  def show_all_events
    @events = Event.all
  end

  def show_all_locations
    @locations = Location.all
  end

  def show_all_users
    @users = User.where.not(first_name: 'guest')
  end

  def new_option_form
    @option = Option.any? ? Option.last : Option.new
  end

  def edit_option_form
    @option = Option.last
  end
end

app/views/html/_location_form.html.erb
<%= form_for @location, url: (current_page?(new_location_form_path) ? create_location_path : update_location_path), method: :post do |f| %>
    <div class="form-group">
      <%= f.label :name, 'Name' %>
      <%= f.text_field :name, class: 'form-control', required: 'true' %>
    </div>
    <div class="form-group">
      <%= f.label :description, 'Description' %>
      <%= f.text_area :description, class: 'form-control', required: 'true' %>
    </div>
    <div class="form-group">
      <%= f.label :coordinates, 'Coordinates' %>
      <%= f.text_field :coordinates, class: 'form-control', required: 'true' %>
    </div>
    <%= f.submit 'Submit', class: 'btn btn-default' %>
<% end %>

app/views/html/_option_form.html.erb
<%= form_for @option, url: (current_page?(new_option_form_path) ? create_option_path : update_option_path), method: :post do |f| %>
    <div class="form-group">
      <%= f.label :logo, 'Logo' %>
      <%= f.text_field :logo, class: 'form-control', required: 'true' %>
    </div>
    <div class="form-group">
      <%= f.label :color, 'Color' %>
      <%= f.text_field :color, class: 'form-control', required: 'true' %>
    </div>
    <%= f.submit 'Submit', class: 'btn btn-default' %>
<% end %>

app/views/html/about_doc.html.erb
<%= provide(:title, 'About') %>
<div class="container">
<div class="row">
<div class="col-md-9 col-centered">
<h3>About</h3>
<div class="row">
<div class="col-md-11 col-md-offset-2 col-centered" style="padding-top:1em;">
<p>Welcome to UNLV's QR Code Scavenger Hunt Site! This application was originally conceived at the UNLV Computer Science Department by Ed Jorgensen and Guymon Hall to help students familiarize themselves with various locations around the UNLV campus. </p>
</div>
</div>
</div>
</div>
<div class="row">
<div class="col-md-9 col-centered">
<h3>Contributors</h3>
<div class="row">
<div class="col-md-11 col-md-offset-2 col-centered" style="padding-top:1em;">
<p>Thank you to the following individuals for their contributions: </p>
</div>
</div>
<div class="row">
<div class="col-md-11 col-md-offset-2 col-centered" style="padding-top:1em;">
<ul>
<li>Megan Freeman</li>
<li>Reiley Porter</li>
<li>Carmon Wong</li>
<li>Beverly Wood</li>
</ul>
</div>
</div>
<div class="row">
<div class="col-md-11 col-md-offset-2 col-centered" style="padding-top:1em;">
<p>To contribute to this project, please contact <code>g u y m o n . h a l l @ u n l v . e d u</code>. </p>
</div>
</div>
</div>
</div>
<div class="row">
<div class="col-md-9 col-centered">
<h3>License</h3>
<div class="row">
<div class="col-md-11 col-md-offset-2 col-centered" style="padding-top:1em;">
<p>This application and its source code are licensed under the MIT License: </p>
</div>
</div>
<div class="row">
<div class="col-md-11 col-md-offset-2 col-centered" style="padding-top:1em;">
<p>Copyright (c) 2016 Guymon Hall </p>
</div>
</div>
<div class="row">
<div class="col-md-11 col-md-offset-2 col-centered" style="padding-top:1em;">
<p>Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions: </p>
</div>
</div>
<div class="row">
<div class="col-md-11 col-md-offset-2 col-centered" style="padding-top:1em;">
<p>The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. </p>
</div>
</div>
<div class="row">
<div class="col-md-11 col-md-offset-2 col-centered" style="padding-top:1em;">
<p>THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. </p>
</div>
</div>
</div>
</div>
</div>

app/views/html/edit_event_form.html.erb
<%= provide(:title, "Editing #{@event.title}") %>

<div class="container">
  <div class="row">
    <div class="col-md-7 col-centered">
      <h3>Edit Event</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-7 col-centered">
      <%= render 'event_form' %>
    </div>
  </div>
</div>

app/views/html/edit_location_form.html.erb
<%= provide(:title, "Editing #{@location.name}") %>

<div class="container">
  <div class="row">
    <div class="col-md-7 col-centered">
      <h3>Edit Location</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-7 col-centered">
      <%= render 'location_form' %>
    </div>
  </div>
</div>

app/views/html/edit_option_form.html.erb
<%= provide(:title, 'Edit Options') %>

<div class="container">
  <div class="row">
    <div class="col-md-7 col-centered">
      <h3>Edit Options</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-7 col-centered">
      <%= render 'option_form' %>
    </div>
  </div>
</div>

app/views/html/edit_user_form.html.erb
<%= provide(:title, 'Edit Account') %>

<div class="container">
  <div class="row">
    <div class="col-md-7 col-centered">
      <h3>Edit Account</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-7 col-centered">
      <%= render 'user_form' %>
    </div>
  </div>
</div>

app/views/html/home.html.erb
<%= provide(:title, 'Home') %>

<div class="container">
  <!-- Page title -->
  <div class="row">
    <div class="col-md-9 col-centered">
      <h3>Events</h3>
    </div>
  </div>

  <!--- Events table -->
  <div class="row">
    <div class="col-md-9 col-centered">
      <div class="table-responsive dashboard-table">
        <table class="table table-hover">
          <thead>
          <tr>
            <th>Event</th>
            <th>Start</th>
            <th>End</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <% if not @current_events.empty? %>
              <% @current_events.each do |event| %>
                  <tr>
                    <td><%= event.title %></td>
                    <td><%= event.start_date.strftime("%b %e, %Y") %></td>
                    <td><%= event.end_date.strftime("%b %e, %Y") %></td>
                    <td><%= link_to 'view', show_event_path(event) %> / <%= link_to 'join', join_event_path(event.id) %></td>
                  </tr>
              <% end %>
          <% end %>

          <% if not @upcoming_events.empty? %>
              <% @upcoming_events.each do |event| %>
                  <tr>
                    <td><%= event.title %></td>
                    <td><%= event.start_date.strftime("%b %e, %Y") %></td>
                    <td><%= event.end_date.strftime("%b %e, %Y") %></td>
                    <td></td>
                  </tr>
              <% end %>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/html/login_form.html.erb
<%= provide(:title, 'Login') %>

<div class="container">
  <div class="row">
    <div class="col-md-7 col-centered">
      <h3>Login</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-7 col-centered">
      <%= form_for @current_user, url: create_session_path, method: :post do |f| %>
          <div class="form-group">
            <%= f.label :email, 'Email' %>
            <%= f.email_field :email, value: nil, class: 'form-control', required: 'true' %>
          </div>
          <div class="form-group">
            <%= f.label :password, 'Password' %>
            <%= f.password_field :password, class: 'form-control', required: 'true' %>
          </div>
          <%= f.submit 'Login', class: 'btn btn-default' %>
          <%= hidden_field_tag :redirect_to, params[:redirect_to] %>
      <% end %>
    </div>
  </div>
</div>

app/views/html/show_all_events.html.erb
<%= provide :title, 'Events Admin' %>

<div class="container">
  <div class="row">
    <div class="col-md-9 col-centered">
      <h3>Events</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-md-9 col-centered">
      <div class="table-responsive dashboard-table">
        <table class="table table-hover">
          <thead>
          <tr>
            <th>Event</th>
            <th>Start</th>
            <th>End</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <% @events.each do |event| %>
              <tr>
                <td><%= event.title %></td>
                <td><%= event.start_date.strftime("%b %e, %Y") %></td>
                <td><%= event.end_date.strftime("%b %e, %Y") %></td>
                <td><%= link_to 'view', show_event_path(event) %> | <%= link_to 'edit', edit_event_form_path(event) %>
                  | <%= link_to 'delete', delete_event_path(event), data: {confirm: 'Are you sure?'} %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-9 col-centered">
      <p class="text-center">
        <%= link_to 'new event', new_event_form_path, class: 'text-center btn btn-default' %>
      </p>
    </div>
  </div>
</div>

app/views/html/show_all_locations.html.erb
<%= provide :title, 'Locations Admin' %>

<div class="container">
  <div class="row">
    <div class="col-md-9 col-centered">
      <h3>Locations</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-md-9 col-centered">
      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
          <tr>
            <th>Location</th>
            <th>Description</th>
            <th></th>
          </tr>
          </thead>

          <tbody>
          <% @locations.each do |location| %>
              <tr>
                <td><%= location.name %></td>
                <td><%= location.description %></td>
                <td>
                  <%= link_to 'view', show_location_path(location) %> |
                  <%= link_to 'edit', edit_location_form_path(location) %> |
                  <%= link_to 'delete', delete_location_path(location) %>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-9 col-centered">
      <p class="text-center">
        <%= link_to 'new location', new_location_form_path, class: 'text-center btn btn-default' %>
      </p>
    </div>
  </div>
</div>

app/views/html/show_all_users.html.erb
<%= provide :title, 'User Admin' %>

<div class="container">
  <div class="row">
    <div class="col-md-9 col-centered">
      <h3>Users</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-md-9 col-centered">
      <div class="table-responsive dashboard-table">
        <table class="table table-hover">
          <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <% @users.each do |user| %>
              <tr>
                <td><%= "#{user.first_name} #{user.last_name}" %></td>
                <td><%= user.email %></td>
                <td><%= link_to 'view', show_user_path(user) %> | <%= link_to 'edit', edit_user_form_path(user) %>
                  | <%= link_to 'delete', delete_user_path(user), data: {confirm: 'Are you sure?'} %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-9 col-centered">
      <p class="text-center">
        <%= link_to 'new user', new_user_form_path, class: 'text-center btn btn-default' %>
      </p>
    </div>
  </div>
</div>

app/views/html/show_event.html.erb
<%= provide(:title, @event.title) %>

<div class="container">
  <div class="row">
    <div class="col-md-9 col-centered">
      <h3>
        <%= @event.title %>
        <% if @current_user.owns? @event or @current_user.admin? %>
            <small>(<%= link_to 'edit', edit_event_form_path(@event) %> | <%= link_to 'delete', delete_event_path(@event), data: { confirm: 'Are you sure?' } %>)</small>
        <% end %>
      </h3>
    </div>
  </div>

  <div class="row">
    <div class="col-md-9 col-centered description">
      <p><%= @event.description %></p>
    </div>
  </div>

  <% if @current_user.owns? @event or @current_user.admin? %>
      <div class="row">
        <div class="col-md-9 col-centered">
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
              <tr>
                <th>Participant</th>
                <th># visited</th>
                <th># unvisited</th>
                <th>% complete</th>
              </thead>

              <tbody>
              <% @event.participants.each do |participant| %>
                  <tr>
                    <td><%= "#{participant.first_name} #{participant.last_name}" %></td>
                    <td><%= participant.visited(@event).size %></td>
                    <td><%= participant.unvisited(@event).size %></td>
                    <td><%= participant.progress(@event) %>%</td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-9 col-centered">
          <hr>
        </div>
      </div>
  <% end %>

  <div class="row">
    <div class="col-md-9 col-centered">
      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
          <tr>
            <th>Location</th>
            <th>Description</th>
            <th></th>
          </tr>
          </thead>

          <tbody>
          <% @event.locations.each do |location| %>
              <tr>
                <td><%= location.name %></td>
                <td><%= location.description %></td>
                <% unless @current_user.owns? @event %>
                    <% if @current_user.visited_locations.include? location %>
                        <td>&#x2714</td>
                    <% else %>
                        <td><%= link_to "map", "http://maps.google.com/?q=#{location.coordinates}", target: "_blank" %></td>
                    <% end %>
                <% else %>
                    <td>
                      <%= link_to 'view', show_location_path(location) %> |
                      <%= link_to 'edit', edit_location_form_path(location) %> |
                      <%= link_to 'delete', delete_location_path(location) %>
                    </td>
                <% end %>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/html/user_doc.html.erb
<%= provide(:title, 'User') %>
<div class="container">
<div class="row">
<div class="col-md-9 col-centered">
<h3>User</h3>
</div>
</div>
<div class="row">
<div class="col-md-9 col-centered">
<h3>Create an account</h3>
<div class="row">
<div class="col-md-11 col-md-offset-2 col-centered" style="padding-top:1em;">
<p>On the homepage, click "signup".  Enter your information and click "submit".  Once your account is created, you will be redirected to your homepage (Dashboard). </p>
</div>
</div>
</div>
</div>
<div class="row">
<div class="col-md-9 col-centered">
<h3>Join an event</h3>
<div class="row">
<div class="col-md-11 col-md-offset-2 col-centered" style="padding-top:1em;">
<p>When logged in, go to the main Homepage.  This will display a list of the active events.  Select an event to join.  Go to your Dashboard to confirm you have joined the event. </p>
</div>
</div>
</div>
</div>
<div class="row">
<div class="col-md-9 col-centered">
<h3>Visit locations</h3>
<div class="row">
<div class="col-md-11 col-md-offset-2 col-centered" style="padding-top:1em;">
<p>Visit each event location.  When you arrive at a given location, scan the available QR code.  When prompted, input your credentials to check in are mark the location as "visited".     </p>
</div>
</div>
</div>
</div>
<div class="row">
<div class="col-md-9 col-centered">
<h3>View your dashboard</h3>
<div class="row">
<div class="col-md-11 col-md-offset-2 col-centered" style="padding-top:1em;">
<p>When logged in, click "Dashboard".  This page displays all events you are participating in, event you own, and items you own.  To view your account details, click on the dropdown tab labelled with your email address.  This will display your account details.  Input any information you wish to update. </p>
</div>
</div>
</div>
</div>
</div>